# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 210)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.line_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_name.setObjectName("line_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_name)
        self.line_roast = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_roast.setObjectName("line_roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_roast)
        self.line_type = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_type.setObjectName("line_type")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_type)
        self.line_describe = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_describe.setObjectName("line_describe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_describe)
        self.line_price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_price.setObjectName("line_price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.line_price)
        self.line_mass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_mass.setObjectName("line_mass")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_mass)
        self.button = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "название"))
        self.label_2.setText(_translate("Dialog", "прожарка"))
        self.label_3.setText(_translate("Dialog", "тип"))
        self.label_4.setText(_translate("Dialog", "описание"))
        self.label_5.setText(_translate("Dialog", "цена"))
        self.label_6.setText(_translate("Dialog", "масса"))
        self.button.setText(_translate("Dialog", "Добавить"))
