# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(255, 172, 247);")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(5, 24, 790, 571))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(10, 10, 10);")
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.but_add_coffee = QtWidgets.QPushButton(Form)
        self.but_add_coffee.setGeometry(QtCore.QRect(0, 0, 400, 23))
        self.but_add_coffee.setStyleSheet("background-color: rgb(238, 229, 255);\n"
"color: rgb(63, 63, 63);")
        self.but_add_coffee.setObjectName("but_add_coffee")
        self.but_edit_coffee = QtWidgets.QPushButton(Form)
        self.but_edit_coffee.setGeometry(QtCore.QRect(400, 0, 400, 23))
        self.but_edit_coffee.setStyleSheet("background-color: rgb(238, 229, 255);\n"
"color: rgb(63, 63, 63);")
        self.but_edit_coffee.setObjectName("but_edit_coffee")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_add_coffee.setText(_translate("Form", "Добавить"))
        self.but_edit_coffee.setText(_translate("Form", "Редактировать"))
